"""empty message

Revision ID: 882c4efd0fb2
Revises: d848d125836d
Create Date: 2020-10-03 02:08:14.716513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '882c4efd0fb2'
down_revision = 'd848d125836d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('set', sa.Column('excercise_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'set', 'exercise', ['excercise_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'set', type_='foreignkey')
    op.drop_column('set', 'excercise_id')
    # ### end Alembic commands ###
